# Generated by Django 3.2.13 on 2023-08-16 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=128)),
                ('text', models.TextField(blank=True, null=True)),
                ('href', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LungPred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=50)),
                ('wheezing', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default='No')),
                ('fatigue', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default='No')),
                ('coughing', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default='No')),
                ('shortness_of_breath', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default='No')),
                ('smoking', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default='No')),
                ('swallowing_difficulty', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default='No')),
                ('result', models.SmallIntegerField()),
                ('fk', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ai.mlmodel')),
            ],
        ),
        migrations.CreateModel(
            name='HivPred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('All', 'All'), ('13 - 19', '13 - 19'), ('20 - 29', '20 - 29'), ('30 - 39', '30 - 39'), ('40 - 49', '40 - 49'), ('50 - 59', '50 - 59'), ('60+', '60+')], default='All', max_length=10)),
                ('gender', models.CharField(choices=[('All', 'All'), ('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], default='Female', max_length=11)),
                ('hiv_diagnoses', models.PositiveIntegerField(default=10)),
                ('plwdhi', models.FloatField(default=0.7)),
                ('linked_to_care', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100)], default=50)),
                ('result', models.FloatField()),
                ('fk', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='ai.mlmodel')),
            ],
        ),
        migrations.CreateModel(
            name='HeartPred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=50)),
                ('sex', models.IntegerField(choices=[(0, 'Female'), (1, 'Male')], default=0)),
                ('cp', models.IntegerField(choices=[(0, 'Asymptomatic'), (1, 'Non-Anginal Pain'), (2, 'Atypical Angina'), (3, 'Typical Angina')], default=0)),
                ('chol', models.PositiveIntegerField(default=150)),
                ('result', models.SmallIntegerField()),
                ('fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ai.mlmodel')),
            ],
        ),
    ]
