# Generated by Django 3.2.13 on 2023-08-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivpred',
            name='age',
            field=models.CharField(choices=[('All', 'All'), ('13 - 19', '13 - 19'), ('20 - 29', '20 - 29'), ('30 - 39', '30 - 39'), ('40 - 49', '40 - 49'), ('50 - 59', '50 - 59'), ('60+', '60+')], default='All', max_length=10),
        ),
    ]
