# Generated by Django 3.2.13 on 2023-08-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_hivpred_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lungpred',
            name='coughing',
            field=models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default='No'),
        ),
        migrations.AlterField(
            model_name='lungpred',
            name='fatigue',
            field=models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default='No'),
        ),
        migrations.AlterField(
            model_name='lungpred',
            name='shortness_of_breath',
            field=models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default='No'),
        ),
        migrations.AlterField(
            model_name='lungpred',
            name='smoking',
            field=models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default='No'),
        ),
        migrations.AlterField(
            model_name='lungpred',
            name='swallowing_difficulty',
            field=models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default='No'),
        ),
        migrations.AlterField(
            model_name='lungpred',
            name='wheezing',
            field=models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default='No'),
        ),
    ]
